[package]
name = "markdown-spike-egui-extended"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
eframe = { version = "0.33", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
egui_commonmark_extended = { version = "0.25", features = ["better_syntax_highlighting"] }
windows-sys = { version = "0.59", features = ["Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }
